name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Version increment check
        run: |
            # Check that the version in package.json has been incremented
            git fetch origin main
            MAIN_VERSION=$(git show origin/main:package.json | jq -r .version)
            CURRENT_VERSION=$(jq -r .version package.json)
            if [ "$MAIN_VERSION" = "$CURRENT_VERSION" ]; then
              echo "Error: Version in package.json has not been incremented. Current version: ${CURRENT_VERSION}, Main version: ${MAIN_VERSION}"
              exit 1
            fi 
            else
              echo "Version check passed. Current version: ${CURRENT_VERSION}, Main version: ${MAIN_VERSION}"
            fi 
      - name: Install dependencies
        run: npm ci
      - name: Npm run test
        run: npm run test
      - name: Validate configuration
        run: npm run validate
